import { StateNode, TLDefaultSizeStyle, TLDrawShape, TLDrawShapeSegment, TLHighlightShape, TLKeyboardEventInfo, TLPointerEventInfo, Vec } from '@tldraw/editor';
import { HighlightShapeUtil } from '../../highlight/HighlightShapeUtil';
import { DrawShapeUtil } from '../DrawShapeUtil';
type DrawableShape = TLDrawShape | TLHighlightShape;
export declare class Drawing extends StateNode {
    static id: string;
    static trackPerformance: boolean;
    info: TLPointerEventInfo;
    initialShape?: DrawableShape;
    shapeType: "draw" | "highlight";
    util: DrawShapeUtil | HighlightShapeUtil;
    isPen: boolean;
    isPenOrStylus: boolean;
    segmentMode: "free" | "starting_free" | "starting_straight" | "straight";
    didJustShiftClickToExtendPreviousShapeLine: boolean;
    pagePointWhereCurrentSegmentChanged: Vec;
    pagePointWhereNextSegmentChanged: Vec | null;
    lastRecordedPoint: Vec;
    mergeNextPoint: boolean;
    currentLineLength: number;
    zoomOnEnter: number;
    currentSegmentPoints: Vec[];
    markId: string | null;
    onEnter(info: TLPointerEventInfo): void;
    onPointerMove(): void;
    onKeyDown(info: TLKeyboardEventInfo): void;
    onKeyUp(info: TLKeyboardEventInfo): void;
    onExit(): void;
    canClose(): boolean;
    getIsClosed(segments: TLDrawShapeSegment[], size: TLDefaultSizeStyle, scale: number, strokeWidth?: number): boolean;
    private startShape;
    private updateDrawingShape;
    private getLineLength;
    onPointerUp(): void;
    onCancel(): void;
    onComplete(): void;
    onInterrupt(): void;
    onLongPress(): void;
    complete(): void;
    cancel(): void;
}
export {};
//# sourceMappingURL=Drawing.d.ts.map