import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { strayAnswers } from '../server/lib/classroom-submission.mjs'

// The fixture is one of Skip's real handouts, generated by his own
// bin/make-handout.py from homework/hw9-causality.qmd. The shape matters: his
// documents are narrative sections with several exercises inside each, so a
// heading is not a problem boundary. An invented fixture with one problem per
// heading made headings look like boundaries and led me to the wrong design.
const handout = fs.readFileSync(
  fileURLToPath(new URL('./fixtures/hw9-causality.handout.qmd', import.meta.url)), 'utf8')

test('the handout as issued has nothing stray in it', () => {
  assert.deepEqual(strayAnswers(handout), [], 'a blank handout was reported as mis-answered')
})

test('an untouched block with nothing after it is a skipped problem, not an error', () => {
  // Skipping a question is allowed; only writing in the wrong place is not.
  const oneAnswered = handout.replace('*(your answer here)*', 'The ATE is the average of tau_i.')
  assert.deepEqual(strayAnswers(oneAnswered), [])
})

test('an answer typed under the box is caught and quoted back', () => {
  const stray = handout.replace(
    /(::: \{#ans-exr-ate \.callout-answer\}\n\n\*\(your answer here\)\*\n\n:::)/,
    '$1\n\nThe ATE is the average of tau_i over everyone in the population.')
  const found = strayAnswers(stray)
  assert.equal(found.length, 1)
  assert.equal(found[0].id, 'ans-exr-ate')
  assert.match(found[0].firstLine, /average of tau_i/)
})

test('answering properly and adding prose under it is not flagged', () => {
  // If the box is filled, text after it is the document's own narrative — his,
  // not theirs — and flagging it would refuse a correct submission.
  const both = handout.replace(
    /(::: \{#ans-exr-ate \.callout-answer\}\n\n)\*\(your answer here\)\*(\n\n:::)/,
    '$1It is the mean of tau_i.$2\n\nSome narrative that follows.')
  assert.deepEqual(strayAnswers(both), [])
})

test('every exercise in the real handout is found', () => {
  // 12 answer blocks; if the parser drifts off his structure this drops.
  const stray = handout.replace(/\*\(your answer here\)\*/g, '')
    .replace(/(:::\n)/g, '$1\nwritten in the wrong place\n')
  assert.ok(strayAnswers(stray).length >= 10, `only found ${strayAnswers(stray).length}`)
})
