export { TocTab, DarkModeToggle } from './TocTab'
export { SearchTab } from './SearchTab'
export { ChangesTab } from './ChangesTab'
export { HistoryTab, HistoryChanges } from './HistoryTab'
export { ProofsTab } from './ProofsTab'
export { NotesTab } from './NotesTab'
