export type Styles = {
    [K in string]?: string;
};
export type ReadonlyStyles = {
    readonly [K in string]?: string;
};
type CanSkipRule = (value: string, property: string, options: {
    currentColor: string;
    defaultStyles: ReadonlyStyles;
    getStyle(property: string): string;
    parentStyles: ReadonlyStyles;
}) => boolean;
export declare const cssRules: {
    'border-block-end-color': CanSkipRule;
    'border-block-end-style': CanSkipRule;
    'border-block-end-width': CanSkipRule;
    'border-block-end': CanSkipRule;
    'border-block-start-color': CanSkipRule;
    'border-block-start-style': CanSkipRule;
    'border-block-start-width': CanSkipRule;
    'border-block-start': CanSkipRule;
    'border-bottom-color': CanSkipRule;
    'border-bottom-style': CanSkipRule;
    'border-bottom-width': CanSkipRule;
    'border-bottom': CanSkipRule;
    'border-collapse': CanSkipRule;
    'border-inline-end-color': CanSkipRule;
    'border-inline-end-style': CanSkipRule;
    'border-inline-end-width': CanSkipRule;
    'border-inline-end': CanSkipRule;
    'border-inline-start-color': CanSkipRule;
    'border-inline-start-style': CanSkipRule;
    'border-inline-start': CanSkipRule;
    'border-left-color': CanSkipRule;
    'border-left-style': CanSkipRule;
    'border-left-width': CanSkipRule;
    'border-left': CanSkipRule;
    'border-right-color': CanSkipRule;
    'border-right-style': CanSkipRule;
    'border-right-width': CanSkipRule;
    'border-right': CanSkipRule;
    'border-spacing': CanSkipRule;
    'border-top-color': CanSkipRule;
    'border-top-style': CanSkipRule;
    'border-top-width': CanSkipRule;
    'border-top': CanSkipRule;
    'caption-side': CanSkipRule;
    'caret-color': CanSkipRule;
    'column-rule-color': CanSkipRule;
    'empty-cells': CanSkipRule;
    'font-family': CanSkipRule;
    'font-size-adjust': CanSkipRule;
    'font-size': CanSkipRule;
    'font-stretch': CanSkipRule;
    'font-style': CanSkipRule;
    'font-variant': CanSkipRule;
    'font-weight': CanSkipRule;
    'letter-spacing': CanSkipRule;
    'line-height': CanSkipRule;
    'list-style-image': CanSkipRule;
    'list-style-position': CanSkipRule;
    'list-style-type': CanSkipRule;
    'list-style': CanSkipRule;
    'outline-color': CanSkipRule;
    'overflow-wrap': CanSkipRule;
    'stroke-linecap': CanSkipRule;
    'stroke-linejoin': CanSkipRule;
    'tab-size': CanSkipRule;
    'text-align-last': CanSkipRule;
    'text-align': CanSkipRule;
    'text-decoration-color': CanSkipRule;
    'text-decoration': (value: string, property: string, { currentColor }: {
        currentColor: string;
        defaultStyles: ReadonlyStyles;
        getStyle(property: string): string;
        parentStyles: ReadonlyStyles;
    }) => boolean;
    'text-emphasis-color': CanSkipRule;
    'text-indent': CanSkipRule;
    'text-justify': CanSkipRule;
    'text-shadow': CanSkipRule;
    'text-transform': CanSkipRule;
    'white-space-collapse': CanSkipRule;
    'white-space': CanSkipRule;
    'word-break': CanSkipRule;
    'word-spacing': CanSkipRule;
    'word-wrap': CanSkipRule;
    cursor: CanSkipRule;
    direction: CanSkipRule;
    font: CanSkipRule;
    orphans: CanSkipRule;
    quotes: CanSkipRule;
    visibility: CanSkipRule;
    widows: CanSkipRule;
};
export {};
//# sourceMappingURL=cssRules.d.ts.map