// What is in a worktree that git will not tell you about.
//
// `git status --porcelain` is blind to ignored files and `git worktree remove`
// does not count them as a reason to refuse, so a worktree holding nothing but
// `scratch/plan.md` reads clean and gets deleted with the plan inside it — and
// `AGENTS.md` tells every agent to put its plans and reports in exactly that
// directory. That is the hole the dev bot's sweep has been disabled pending.
//
// Skip, 2026-08-13, on what the sweep is for: *"I thought they were supposed to
// fucking remove node modules and shit"*, and on it taking `scratch/`:
// *"That's fucked."* So the rule is not "any ignored file protects a worktree" —
// that would disable the sweep entirely, because every worktree has
// `node_modules`. It is: **build output is reclaimable, authored content is not.**
//
// THE DEFAULT IS KEEP. An ignored path nobody has classified is treated as
// somebody's work, not as cruft. Getting that backwards deletes a file whose
// only copy was in a directory we were told to write to; getting it right costs
// disk. The asymmetry is the whole design.

// Reclaimable: regenerated by a build, a package manager, or a test run. Nothing
// here is ever the only copy of anything.
//
// Matched against the FIRST path segment for a directory entry, or the whole
// basename for a file. `git status --ignored` collapses an ignored directory to
// `dir/`, which is what this reads.
const RECLAIMABLE_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  'coverage',
  'test-results',
  'playwright-report',
  '.cache',
  '.parcel-cache',
  '.turbo',
  '.next',
  '.vite',
  '.pytest_cache',
  '__pycache__',
  '.venv',
  'venv',
]);

const RECLAIMABLE_FILE_PATTERNS = [
  /^\.DS_Store$/,
  /\.tsbuildinfo$/,
  /^npm-debug\.log(\.\d+)?$/,
  /^yarn-error\.log$/,
  /^\.eslintcache$/,
];

// Named because Skip named them, and because AGENTS.md points agents at them.
// They are not needed for correctness — the default already keeps them — but a
// reader asking "is my scratch directory safe" should find the answer here
// rather than infer it from an absent entry.
const AUTHORED_HINTS = ['scratch/', 'TODO', '.claude/'];

/** One ignored path, as `git status --ignored` reports it, classified. */
export function classifyIgnoredPath(rawPath) {
  const path = String(rawPath || '').trim().replace(/^"|"$/g, '');
  if (!path) return { path, reclaimable: false, why: 'empty path' };

  const isDirectory = path.endsWith('/');
  const segments = path.replace(/\/$/, '').split('/').filter(Boolean);
  const first = segments[0] || '';
  const basename = segments[segments.length - 1] || '';

  // A reclaimable directory anywhere in the path makes the whole entry
  // reclaimable: `packages/bot/node_modules/` is still node_modules.
  if (segments.some(segment => RECLAIMABLE_DIRS.has(segment))) {
    return { path, reclaimable: true, why: `build output (${first})` };
  }
  if (!isDirectory && RECLAIMABLE_FILE_PATTERNS.some(pattern => pattern.test(basename))) {
    return { path, reclaimable: true, why: `build artifact (${basename})` };
  }
  const hint = AUTHORED_HINTS.find(h => path.startsWith(h));
  return {
    path,
    reclaimable: false,
    why: hint ? `authored content (${hint})` : 'unclassified — treated as authored',
  };
}

/**
 * Decide whether a worktree's ignored content is all reclaimable.
 *
 * `lines` is the raw output of `git status --porcelain --ignored` — the
 * `traditional` form, which collapses an ignored directory to `dir/` rather than
 * listing every file under it. That matters: `--ignored=matching` on this repo
 * enumerates thousands of paths under `scratch/` alone.
 *
 * Returns `{ safeToRemove, authored, reclaimable }`. `authored` is the list a
 * caller should log — "kept because of these" is the sentence somebody needs
 * when they ask why the sweep left a worktree alone.
 */
export function classifyWorktreeIgnored(lines) {
  const paths = String(lines || '')
    .split('\n')
    .map(line => line.trimEnd())
    .filter(line => line.startsWith('!! '))
    .map(line => line.slice(3));

  const authored = [];
  const reclaimable = [];
  for (const path of paths) {
    const verdict = classifyIgnoredPath(path);
    (verdict.reclaimable ? reclaimable : authored).push(verdict);
  }
  return { safeToRemove: authored.length === 0, authored, reclaimable };
}

/** The git invocation this reads, so a caller cannot accidentally pass the wrong one. */
export const IGNORED_STATUS_ARGS = ['status', '--porcelain', '--ignored'];
