import { test } from 'node:test'
import assert from 'node:assert/strict'
import { JSDOM } from 'jsdom'
import { markQuartoSourceLines } from './quarto-source-lines.mjs'

/** Quarto's content container, which is what the marker walk is scoped to. */
function quartoPage(body) {
  return `<!doctype html><html><body>
    <nav id="TOC"><ul><li>Sampling</li><li>Estimation</li></ul></nav>
    <main id="quarto-document-content">${body}</main>
  </body></html>`
}

function markers(html) {
  const { document } = new JSDOM(html).window
  return [...document.querySelectorAll('[data-source-line]')].map(element => ({
    tag: element.tagName,
    line: Number(element.getAttribute('data-source-line')),
    text: (element.textContent || '').replace(/\s+/g, ' ').trim(),
  }))
}

test('a rendered block is marked with the source line it was written on', () => {
  const source = [
    '---',                                    // 1
    'title: "Sampling"',                      // 2
    '---',                                    // 3
    '',                                       // 4
    '# Estimating a mean',                    // 5
    '',                                       // 6
    'The sample mean is an estimator.',       // 7
  ].join('\n')
  const html = quartoPage('<h1>Estimating a mean</h1><p>The sample mean is an estimator.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)), [
    { tag: 'H1', line: 5, text: 'Estimating a mean' },
    { tag: 'P', line: 7, text: 'The sample mean is an estimator.' },
  ])
})

test('a soft-wrapped paragraph is marked with the line it starts on', () => {
  // Quarto renders these three source lines as one <p>. Matching a rendered
  // block against a single source line missed every paragraph written this way,
  // which is most of them.
  const source = [
    '# Heading',                              // 1
    '',                                       // 2
    'The estimator is unbiased, which is a',  // 3
    'statement about its average over',       // 4
    'repeated samples.',                      // 5
  ].join('\n')
  const html = quartoPage('<h1>Heading</h1><p>The estimator is unbiased, which is a statement about its average over repeated samples.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [1, 3])
})

test('markup that renders away does not stop a block matching', () => {
  const source = [
    'Write $\\theta$ for the estimand --- the thing we are after.', // 1
  ].join('\n')
  // Rendered: math delimiters become \( \), the triple dash becomes an em dash.
  const html = quartoPage('<p>Write \\(\\theta\\) for the estimand — the thing we are after.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [1])
})

test('a callout prefix generated by Quarto does not stop the author text matching', () => {
  const source = [
    '::: {.callout-note}',                    // 1
    'Roll the die thirty times and record what comes up.', // 2
    ':::',                                    // 3
  ].join('\n')
  const html = quartoPage('<div class="callout"><p>Exercise 1 Roll the die thirty times and record what comes up.</p></div>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [2])
})

test('a block with no line in this source gets no marker rather than a guessed one', () => {
  const source = ['# Real heading', '', 'Real prose.'].join('\n')
  const html = quartoPage('<h1>Real heading</h1><p>Real prose.</p><p>Text produced by a lua filter.</p>')

  const found = markers(markQuartoSourceLines(html, source))
  assert.deepEqual(found.map(m => m.line), [1, 3])
  assert.equal(found.some(m => m.text === 'Text produced by a lua filter.'), false)
})

test('marks are monotonic, so a phrase repeated later cannot drag an anchor backwards', () => {
  const source = [
    'The same sentence.',                     // 1
    '',                                       // 2
    'Something in between that is long enough to match on its own.', // 3
    '',                                       // 4
    'The same sentence.',                     // 5
  ].join('\n')
  const html = quartoPage('<p>The same sentence.</p><p>Something in between that is long enough to match on its own.</p><p>The same sentence.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [1, 3, 5])
})

test('output of an executed chunk is left unmarked', () => {
  // The rendered text comes from data, not from a line anyone can annotate.
  const source = ['The table below is computed.', '', '| a | b |', '| - | - |'].join('\n')
  const html = quartoPage('<p>The table below is computed.</p><div class="cell-output"><p>The table below is computed.</p></div>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).length, 1)
})

// A source region the HTML walk can never match must not be offered to it. The
// failure is a FALSE ANCHOR, not a missed one: the cursor sits on an unmatchable
// block and the next real paragraph claims its line. Monotonicity does not save
// this — it bounds how far the anchor can be dragged, not whether it is right.

test('fenced code content does not steal the anchor of prose repeating it', () => {
  const source = [
    '```',                                        // 1
    'A repeated sentence that belongs to code.',  // 2
    '```',                                        // 3
    '',                                           // 4
    'A repeated sentence that belongs to code.',  // 5
  ].join('\n')
  // Quarto renders the first into pre > code, which is not markable; only the
  // second becomes a <p>. So the paragraph is line 5, never line 2.
  const html = quartoPage('<pre><code>A repeated sentence that belongs to code.</code></pre><p>A repeated sentence that belongs to code.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [5])
})

test('a tilde fence and an info string close the same way', () => {
  const source = [
    '~~~{r}',                        // 1
    'plot(x)  # a long enough line', // 2
    '~~~',                           // 3
    '',                              // 4
    'plot(x)  # a long enough line', // 5
  ].join('\n')
  const html = quartoPage('<pre><code>plot(x)  # a long enough line</code></pre><p>plot(x)  # a long enough line</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [5])
})

test('table rows do not steal the anchor of prose repeating them', () => {
  const source = [
    '| An unusually wordy table cell |',  // 1
    '| --- |',                            // 2
    '',                                   // 3
    'An unusually wordy table cell',      // 4
  ].join('\n')
  const html = quartoPage('<table><tr><td>An unusually wordy table cell</td></tr></table><p>An unusually wordy table cell</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [4])
})

test('YAML frontmatter does not steal the anchor of prose repeating it', () => {
  const source = [
    '---',                                  // 1
    'title: "The Idea of Calibration"',     // 2
    '---',                                  // 3
    '',                                     // 4
    '# The Idea of Calibration',            // 5
  ].join('\n')
  const html = quartoPage('<h1>The Idea of Calibration</h1>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [5])
})

test('an unmatched display-math block does not steal the anchor of the prose after it', () => {
  // Display math is one of the structural misses: it is written across several
  // lines between `$$` fences and its rendered text does not compare equal, so
  // it gets no marker. What matters is that the miss stays a miss — the prose
  // that follows must still anchor to its OWN line, not inherit the math's.
  const source = [
    'Before the display, a sentence long enough to match.', // 1
    '',                                                      // 2
    '$$',                                                    // 3
    '\\hat\\theta_n = \\frac{1}{n}\\sum_i Y_i',              // 4
    '$$',                                                    // 5
    '',                                                      // 6
    'After the display, another sentence long enough.',      // 7
  ].join('\n')
  const html = quartoPage('<p>Before the display, a sentence long enough to match.</p><p>\\[\\hat\\theta_n = \\frac{1}{n}\\sum_i Y_i\\]</p><p>After the display, another sentence long enough.</p>')

  // Line 1 and line 7 anchor; the math paragraph is left unmarked rather than
  // given a guessed line.
  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [1, 7])
})

test('prose after a code block still anchors to its own line', () => {
  // The skip must not swallow what follows the fence.
  const source = [
    '```{r}',                                     // 1
    'x <- 1',                                     // 2
    '```',                                        // 3
    '',                                           // 4
    'The chunk above computes something useful.', // 5
  ].join('\n')
  const html = quartoPage('<pre><code>x &lt;- 1</code></pre><p>The chunk above computes something useful.</p>')

  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [5])
})

test('a document without the Quarto content container is returned unchanged', () => {
  // A reveal deck and the book's redirect stub both lack it, and neither takes
  // the line-anchored path. Absence is meaningful, not an error.
  const stub = '<!doctype html><html><head><title>Redirect</title></head><body></body></html>'
  assert.equal(markQuartoSourceLines(stub, '# Heading'), stub)
})

test('a marker already present is left alone', () => {
  const source = ['Author prose here, long enough to match.'].join('\n')
  const html = quartoPage('<p data-source-line="99">Author prose here, long enough to match.</p>')
  assert.deepEqual(markers(markQuartoSourceLines(html, source)).map(m => m.line), [99])
})
