/**
 * Shared source file definitions for ctd CLI.
 *
 * Single source of truth for which files constitute a TeX project
 * and how to encode them for upload.
 */

import { readdirSync, readFileSync, existsSync } from 'fs'
import { join, extname } from 'path'

// Extensions that are part of a TeX project
export const SOURCE_EXTENSIONS = new Set([
  '.tex', '.bib', '.sty', '.cls', '.bst', '.def',            // TeX source
  '.svg', '.png', '.jpg', '.jpeg', '.eps',                     // Figures (no PDFs — those are compiled output)
  '.tikz', '.pgf', '.dtx', '.ins', '.fd',                    // TeX extras
])

// Text extensions (read as utf8); everything else is binary (base64)
const TEXT_EXTENSIONS = new Set([
  '.tex', '.bib', '.sty', '.cls', '.bst', '.def', '.bbl',
  '.tikz', '.pgf', '.dtx', '.ins', '.fd',
])

// Files generated by LaTeX that should be ignored by the watcher
export const JUNK_PATTERNS = [
  '.aux', '.log', '.out', '.synctex', '.fls', '.fdb',
  '.bbl', '.blg', '.bcf', '.run.xml', '.toc', '.lof', '.lot',
  '.nav', '.snm', '.vrb', '.dvi', '.fmt', '_fmt.',
]

/** Check if a file extension is a project source file. */
export function isSourceFile(filename) {
  return SOURCE_EXTENSIONS.has(extname(filename))
}

/** Check if a file should be ignored by the watcher. */
export function isJunk(filename) {
  return JUNK_PATTERNS.some(j => filename.includes(j))
}

/** Read a source file and encode it for upload (utf8 or base64). */
export function readForUpload(fullPath) {
  const ext = extname(fullPath)
  if (TEXT_EXTENSIONS.has(ext)) {
    return { content: readFileSync(fullPath, 'utf8') }
  }
  return { content: readFileSync(fullPath).toString('base64'), encoding: 'base64' }
}

/** Recursively collect all source files in a directory, encoded for upload. */
export function collectSourceFiles(dir) {
  const files = []
  walk(dir, dir, files)
  return files
}

function walk(root, dir, files) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '_site') continue
      walk(root, full, files)
    } else {
      if (!SOURCE_EXTENSIONS.has(extname(entry.name))) continue
      const rel = full.slice(root.length + 1)
      files.push({ path: rel, ...readForUpload(full) })
    }
  }
}
