/**
 * CanvasClipPanel — fork-viewport panel that shows a clipped region of the
 * main canvas. Used by ChangePreviewPanel, AnnotationViewer, ScreenshotCapture,
 * FleetHUD, FleetDocViewShape, and BuildErrorOverlay.
 *
 * Uses the tldraw fork's multi-viewport API:
 * - Registers a named viewport with the main editor
 * - Renders shapes visible to that viewport via getRenderingShapes({ viewportId })
 * - Independent camera without duplicating the store
 *
 * This replaces the old copy-store approach (separate editor + bidirectional sync).
 */
import { useCallback, useEffect, useMemo, useRef, useState, type WheelEvent as ReactWheelEvent } from 'react'
import { TldrawViewport, Vec, stopEventPropagation } from 'tldraw'
import type { Editor, TLAnyShapeUtilConstructor, TLStateNodeConstructor, TLShape, TLViewportId } from 'tldraw'
import {
  canvasClipSurfaceCamera,
  createCanvasClipPanelPlan,
  getOptionalCanvasClipViewport,
  sameCanvasClipCamera,
  setCanvasClipSurfaceCamera,
  type CanvasClipWMSurface,
} from './wm/canvas-clip-panel'
import {
  cameraToCoordinateTransform,
  ensureLayer,
  registerViewportLayer,
  removeLayers,
  unregisterViewportLayer,
  viewportCoordinateLayerId,
  viewportFrameLayerId,
} from './wm/editor-wm'
import { VisibilityViewportProvider } from './shapes/useIsInViewport'
import { canvasClipWheelCamera, isCanvasClipWheelMessage } from './canvas-clip-wheel'
import './CanvasClipPanel.css'

const DEFAULT_WIDTH = 600
const DEFAULT_MAX_HEIGHT_FRACTION = 0.4
const MIN_VISIBLE_LINES = 5
const LINE_HEIGHT_ESTIMATE = 14 // ~12pt in PDF coordinates

const wmSurfaceRegistry = new Map<string, {
  surface: CanvasClipWMSurface
  setCamera: (camera: { x: number; y: number; z: number }) => void
  syncViewportCamera: (camera: { x: number; y: number; z: number }) => void
  syncCoordinateCamera: (camera: { x: number; y: number; z: number }) => void
}>()

function applyViewportCameraToDom(canvas: HTMLDivElement | null, camera: { x: number; y: number; z: number }) {
  const htmlLayer = canvas?.querySelector<HTMLElement>('.tl-html-layer.tl-shapes')
  if (!htmlLayer) return
  htmlLayer.style.transform = `scale(${camera.z}) translate(${camera.x}px,${camera.y}px)`
}

function isEditableWheelTarget(target: Element) {
  return !!target.closest('input, textarea, select, button, a, [contenteditable="true"], [role="button"]')
}

function dispatchMainCanvasWheel(mainEditor: Editor, e: WheelEvent) {
  mainEditor.focus({ focusContainer: false })
  mainEditor.dispatch({
    type: 'wheel',
    name: 'wheel',
    delta: new Vec(-e.deltaX, -e.deltaY, 0),
    point: new Vec(e.clientX, e.clientY),
    shiftKey: e.shiftKey,
    altKey: e.altKey,
    ctrlKey: e.metaKey || e.ctrlKey,
    metaKey: e.metaKey,
    accelKey: e.metaKey || e.ctrlKey,
  })
}

function clampClipCameraToBounds(
  camera: { x: number; y: number; z: number },
  bounds: ClipBounds | null,
  panelWidth: number,
  canvasHeight: number,
) {
  if (!bounds) return camera
  const z = camera.z || 1
  const visibleW = panelWidth / z
  const visibleH = canvasHeight / z
  const maxX = -bounds.x
  const minX = -(bounds.x + Math.max(0, bounds.w - visibleW))
  const maxY = -bounds.y
  const minY = -(bounds.y + Math.max(0, bounds.h - visibleH))
  return {
    ...camera,
    x: Math.min(maxX, Math.max(minX, camera.x)),
    y: Math.min(maxY, Math.max(minY, camera.y)),
  }
}

export function syncCanvasClipPanelViewportCamera(
  viewportId: string,
  camera: { x: number; y: number; z: number },
): boolean {
  const registered = wmSurfaceRegistry.get(viewportId)
  if (!registered) return false
  registered.syncViewportCamera(camera)
  return true
}

export interface ClipBounds {
  x: number
  y: number
  w: number
  h: number
}

interface CanvasClipPanelProps {
  mainEditor: Editor
  bounds: ClipBounds | null
  // Legacy props (accepted but ignored — kept for consumer compatibility)
  shapeUtils?: TLAnyShapeUtilConstructor[]
  tools?: TLStateNodeConstructor[]
  licenseKey?: string
  panelWidth?: number
  maxHeightFraction?: number
  className?: string
  lockCamera?: boolean
  initialTool?: string
  onEditorMount?: (editor: Editor | null) => void
  emphasizeShapeIds?: string[]
  readOnly?: boolean
  liveEdit?: boolean
  wmSurface?: CanvasClipWMSurface
  fullViewport?: boolean
  disableCulling?: boolean
  shapePredicate?: (shape: TLShape) => boolean
  customGestureActiveRef?: { current: boolean }
  requestedShapeIds?: string[]
  requestedShapeTypes?: string[]
  interactionMode?: 'preview' | 'pinned'
  /** External viewport ID (generated by parent). If not provided, generates one internally. */
  viewportId?: string
  children?: React.ReactNode
}

export function CanvasClipPanel({
  mainEditor,
  bounds,
  panelWidth = DEFAULT_WIDTH,
  maxHeightFraction = DEFAULT_MAX_HEIGHT_FRACTION,
  className,
  lockCamera = false,
  wmSurface,
  fullViewport = false,
  disableCulling = false,
  readOnly = false,
  onEditorMount,
  requestedShapeIds,
  interactionMode = 'preview',
  shapePredicate: hostShapePredicate,
  viewportId: externalViewportId,
  children,
}: CanvasClipPanelProps) {
  const panelRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLDivElement>(null)
  const generatedViewportId = useMemo(() => `clip-panel-${Math.random().toString(36).slice(2, 9)}`, [])
  const viewportId = externalViewportId ?? generatedViewportId

  useEffect(() => {
    const shouldRouteWheel = (fullViewport && lockCamera) || readOnly
    if (!shouldRouteWheel) return
    const panel = panelRef.current
    if (!panel) return

    const onWheelCapture = (e: WheelEvent) => {
      const target = e.target instanceof Element ? e.target : null
      if (!target || e.ctrlKey || e.metaKey) return

      const chat = target.closest('.fleet-chat-shape') as HTMLElement | null
      if (chat) {
        const log = target.closest('.fleet-chat-log') as HTMLElement | null
        if (!log) {
          if (Math.abs(e.deltaX) > Math.abs(e.deltaY) && !isEditableWheelTarget(target)) {
            e.preventDefault()
            e.stopPropagation()
            e.stopImmediatePropagation()
            dispatchMainCanvasWheel(mainEditor, e)
          }
          return
        }
        if (log.scrollHeight <= log.clientHeight) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        log.scrollTop += e.deltaY
        log.dispatchEvent(new CustomEvent('fleet-user-scroll'))
        return
      }

      const docview = target.closest('.fleet-docview') as HTMLElement | null
      if (docview) {
        const viewportHost = (target.closest('[data-viewport-id]') || docview.querySelector('[data-viewport-id]')) as HTMLElement | null
        const nestedViewportId = viewportHost?.dataset.viewportId as TLViewportId | undefined
        if (!nestedViewportId) return
        const registered = getOptionalCanvasClipViewport(mainEditor, nestedViewportId)
        if (!registered) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        const z = registered.camera.z || 1
        const nextCamera = {
          ...registered.camera,
          x: registered.camera.x - e.deltaX / z,
          y: registered.camera.y - e.deltaY / z,
        }
        const nestedSurface = wmSurfaceRegistry.get(nestedViewportId)
        if (nestedSurface) nestedSurface.setCamera(nextCamera)
      }
    }

    panel.addEventListener('wheel', onWheelCapture, { capture: true, passive: false })
    return () => panel.removeEventListener('wheel', onWheelCapture, { capture: true })
  }, [fullViewport, lockCamera, mainEditor, readOnly])

  useEffect(() => {
    if (!wmSurface) return
    const coordinateLayerId = viewportCoordinateLayerId(viewportId as TLViewportId)
    const syncCoordinateCamera = (camera: { x: number; y: number; z: number }) => {
      if (wmSurface.wm.hasLayer(coordinateLayerId)) {
        wmSurface.wm.setTransform(coordinateLayerId, cameraToCoordinateTransform(camera))
      }
    }
    const syncViewportCamera = (camera: { x: number; y: number; z: number }) => {
      syncCoordinateCamera(camera)
      const viewport = getOptionalCanvasClipViewport(mainEditor, viewportId as TLViewportId)
      if (viewport?.screenBounds) {
        mainEditor.updateViewport(viewportId as TLViewportId, { camera })
      }
      applyViewportCameraToDom(canvasRef.current, camera)
    }
    const setCamera = (camera: { x: number; y: number; z: number }) => {
      setCanvasClipSurfaceCamera(wmSurface, camera)
      syncViewportCamera(canvasClipSurfaceCamera(wmSurface, fullViewport))
    }
    wmSurfaceRegistry.set(viewportId, { surface: wmSurface, setCamera, syncViewportCamera, syncCoordinateCamera })
    return () => {
      const registered = wmSurfaceRegistry.get(viewportId)
      if (registered?.surface === wmSurface) wmSurfaceRegistry.delete(viewportId)
    }
  }, [mainEditor, viewportId, wmSurface, fullViewport])

  // Expose the main editor to consumers via onEditorMount.
  // With the fork viewport there is no separate overlay editor — consumers
  // use the main editor + viewportId for viewport-specific queries.
  useEffect(() => {
    onEditorMount?.(mainEditor ?? null)
    return () => { onEditorMount?.(null) }
  }, [mainEditor, onEditorMount])

  // Compute camera from bounds or use WM surface. Deduplicate by value: when
  // FleetHUD re-renders (e.g. on fleetBounds recalc) the source produces a new
  // camera object with the same x/y/z. Without dedup, TldrawViewport receives a
  // new camera prop reference, re-registers the viewport, and useIsInViewport's
  // useValue recomputes — which can briefly flip isInViewport false, unmounting
  // FleetChatInner/FleetAgentsInner (the remount bug, 2026-06-22, commit 1517e737).
  const stableCameraRef = useRef<{ x: number; y: number; z: number } | null>(null)
  const [interactiveCamera, setInteractiveCamera] = useState<{ x: number; y: number; z: number } | null>(null)
  const plannedCamera = (() => {
    const next = (() => {
      if (wmSurface) return canvasClipSurfaceCamera(wmSurface, fullViewport)
      if (!bounds) return { x: 0, y: 0, z: 1 }
      return createCanvasClipPanelPlan({
        bounds, panelWidth, viewportHeight: window.innerHeight,
        maxHeightFraction, lockCamera,
        minVisibleLines: MIN_VISIBLE_LINES, lineHeightEstimate: LINE_HEIGHT_ESTIMATE,
      }).camera
    })()
    const prev = stableCameraRef.current
    if (prev && prev.x === next.x && prev.y === next.y && prev.z === next.z) return prev
    stableCameraRef.current = next
    return next
  })()
  const camera = interactiveCamera ?? plannedCamera

  useEffect(() => {
    setInteractiveCamera(null)
  }, [plannedCamera])

  useEffect(() => {
    if (!wmSurface) return
    const frameLayerId = viewportFrameLayerId(viewportId as TLViewportId)
    const coordinateLayerId = viewportCoordinateLayerId(viewportId as TLViewportId)
    const readFrame = () => {
      const currentRect = panelRef.current?.getBoundingClientRect()
      return {
        x: fullViewport ? 0 : currentRect?.left ?? 0,
        y: fullViewport ? 0 : currentRect?.top ?? 0,
        scale: 1,
      }
    }
    ensureLayer(wmSurface.wm, frameLayerId, {
      parent: wmSurface.wm.rootLayerId,
      policy: { x: 'pin', y: 'pin', zoom: 'lock' },
      transform: readFrame(),
    })
    ensureLayer(wmSurface.wm, coordinateLayerId, {
      parent: frameLayerId,
      policy: { x: 'pin', y: 'pin', zoom: 'lock' },
      transform: cameraToCoordinateTransform(camera),
      camera: { x: 0, y: 0, z: 1 },
    })
    const registration = {
      viewportId: viewportId as TLViewportId,
      wm: wmSurface.wm,
      frameLayerId,
      coordinateLayerId,
      surfaceLayerId: wmSurface.layerId,
      readFrame,
    }
    registerViewportLayer(mainEditor, registration)
    return () => {
      unregisterViewportLayer(mainEditor, viewportId as TLViewportId, registration)
      removeLayers(wmSurface.wm, [coordinateLayerId, frameLayerId])
    }
  }, [mainEditor, wmSurface, viewportId, fullViewport, camera.x, camera.y, camera.z])

  // Panel height: at least 5 lines, at most maxHeightFraction of viewport
  const canvasHeight = useMemo(() => {
    if (!bounds) return 100
    const zoom = panelWidth / bounds.w
    const contentH = bounds.h * zoom
    const minH = MIN_VISIBLE_LINES * LINE_HEIGHT_ESTIMATE * zoom
    return Math.max(minH, Math.min(contentH, window.innerHeight * maxHeightFraction))
  }, [bounds, panelWidth, maxHeightFraction])

  useEffect(() => {
    if (!readOnly || !bounds) return
    const panel = panelRef.current
    if (!panel) return
    const active = new Map<number, { x: number; y: number }>()
    let lastCenter: { x: number; y: number } | null = null

    const center = () => {
      const points = [...active.values()]
      if (points.length === 0) return null
      return {
        x: points.reduce((sum, p) => sum + p.x, 0) / points.length,
        y: points.reduce((sum, p) => sum + p.y, 0) / points.length,
      }
    }
    const shouldHandle = (e: PointerEvent) =>
      (e.pointerType === 'touch' || e.pointerType === 'pen') &&
      e.target instanceof Element &&
      !isEditableWheelTarget(e.target)

    const onPointerDown = (e: PointerEvent) => {
      if (!shouldHandle(e)) return
      active.set(e.pointerId, { x: e.clientX, y: e.clientY })
      lastCenter = center()
      try { panel.setPointerCapture(e.pointerId) } catch {
        // Pointer capture can fail for synthetic/cancelled touches; panel listeners still pan without it.
      }
      e.preventDefault()
      e.stopPropagation()
      e.stopImmediatePropagation()
    }
    const onPointerMove = (e: PointerEvent) => {
      if (!active.has(e.pointerId)) return
      active.set(e.pointerId, { x: e.clientX, y: e.clientY })
      const nextCenter = center()
      if (!lastCenter || !nextCenter) {
        lastCenter = nextCenter
        return
      }
      const dx = nextCenter.x - lastCenter.x
      const dy = nextCenter.y - lastCenter.y
      lastCenter = nextCenter
      setInteractiveCamera(prev => {
        const base = prev ?? plannedCamera
        const z = base.z || 1
        return clampClipCameraToBounds({
          ...base,
          x: base.x + dx / z,
          y: base.y + dy / z,
        }, bounds, panelWidth, canvasHeight)
      })
      e.preventDefault()
      e.stopPropagation()
      e.stopImmediatePropagation()
    }
    const onPointerUp = (e: PointerEvent) => {
      if (!active.has(e.pointerId)) return
      active.delete(e.pointerId)
      lastCenter = center()
      try { panel.releasePointerCapture(e.pointerId) } catch {
        // Release can fail after browser-cancelled touches; there is no retained capture to clean up.
      }
      e.preventDefault()
      e.stopPropagation()
      e.stopImmediatePropagation()
    }
    panel.addEventListener('pointerdown', onPointerDown, { capture: true })
    panel.addEventListener('pointermove', onPointerMove, { capture: true })
    panel.addEventListener('pointerup', onPointerUp, { capture: true })
    panel.addEventListener('pointercancel', onPointerUp, { capture: true })
    return () => {
      panel.removeEventListener('pointerdown', onPointerDown, { capture: true })
      panel.removeEventListener('pointermove', onPointerMove, { capture: true })
      panel.removeEventListener('pointerup', onPointerUp, { capture: true })
      panel.removeEventListener('pointercancel', onPointerUp, { capture: true })
    }
  }, [bounds, canvasHeight, panelWidth, plannedCamera, readOnly])

  const handleReadOnlyWheelCapture = useCallback((e: ReactWheelEvent<HTMLDivElement>) => {
    if (!readOnly || !bounds) return
    e.preventDefault()
    stopEventPropagation(e)
    setInteractiveCamera(prev => {
      const base = prev ?? plannedCamera
      return canvasClipWheelCamera(base, e.deltaX, e.deltaY, bounds, panelWidth, canvasHeight, {
        zoom: e.ctrlKey || e.metaKey,
      })
    })
  }, [bounds, canvasHeight, panelWidth, plannedCamera, readOnly])

  const requestedShapeIdsKey = useMemo(
    () => (requestedShapeIds || []).join('\0'),
    [requestedShapeIds],
  )

  useEffect(() => {
    if (!readOnly || !requestedShapeIds || requestedShapeIds.length === 0) return
    const ids = new Set(requestedShapeIds)
    const onMessage = (e: MessageEvent) => {
      if (!isCanvasClipWheelMessage(e.data, viewportId, ids)) return
      const deltaX = Number(e.data.deltaX || 0)
      const deltaY = Number(e.data.deltaY || 0)
      if (!Number.isFinite(deltaX) || !Number.isFinite(deltaY)) return
      setInteractiveCamera(prev => {
        const base = prev ?? plannedCamera
        return canvasClipWheelCamera(base, deltaX, deltaY, bounds, panelWidth, canvasHeight, {
          zoom: !!e.data.ctrlKey || !!e.data.metaKey,
        })
      })
    }
    window.addEventListener('message', onMessage)
    return () => window.removeEventListener('message', onMessage)
  }, [bounds, canvasHeight, panelWidth, plannedCamera, readOnly, requestedShapeIdsKey, viewportId])

  useEffect(() => {
    if (!readOnly) return
    const canvas = canvasRef.current
    if (!canvas) return
    let raf = 0
    const postOwner = (owner: 'clip' | 'page') => {
      const iframes = canvas.querySelectorAll('iframe')
      for (const iframe of iframes) {
        iframe.contentWindow?.postMessage({
          type: 'tlda-wheel-owner',
          owner,
          viewportId,
        }, '*')
      }
    }
    const scheduleClipOwner = () => {
      cancelAnimationFrame(raf)
      raf = requestAnimationFrame(() => postOwner('clip'))
    }
    const onLoad = (event: Event) => {
      if (event.target instanceof HTMLIFrameElement) scheduleClipOwner()
    }
    const observer = new MutationObserver(scheduleClipOwner)
    canvas.addEventListener('load', onLoad, true)
    observer.observe(canvas, { childList: true, subtree: true })
    scheduleClipOwner()
    return () => {
      cancelAnimationFrame(raf)
      observer.disconnect()
      canvas.removeEventListener('load', onLoad, true)
      postOwner('page')
    }
  }, [readOnly, viewportId, requestedShapeIdsKey])

  if (!bounds && !wmSurface) return null

  // Shape predicate: filter shapes based on mode
  const shapePredicate = useMemo(() => {
    if (!lockCamera && !readOnly) return undefined

    return (shape: TLShape) => {
      if (lockCamera) return hostShapePredicate?.(shape) ?? false

      // In readOnly mode, render all shapes
      return true
    }
  }, [hostShapePredicate, lockCamera, readOnly])

  const viewportEl = (
    <VisibilityViewportProvider viewportId={viewportId} keepMounted={disableCulling}>
      <TldrawViewport
        id={viewportId}
        camera={camera}
        className={className}
        disableCulling={disableCulling}
        shapePredicate={shapePredicate}
        onCameraChange={lockCamera ? undefined : (newCam) => {
          setInteractiveCamera(prev => sameCanvasClipCamera(prev, newCam) ? prev : newCam)
        }}
      />
    </VisibilityViewportProvider>
  )

  if (fullViewport) {
    return (
      <div
        ref={panelRef}
        className={`clip-panel clip-panel-fullvp ${className || ''}`}
        data-viewport-id={viewportId}
        data-wm-surface-id={wmSurface?.surfaceId}
        data-wm-layer-id={wmSurface?.layerId}
        style={{
          position: 'fixed',
          inset: 0,
          width: '100vw',
          height: '100vh',
          pointerEvents: 'none',
          background: 'transparent',
          boxShadow: 'none',
          borderRadius: 0,
          overflow: 'visible',
        }}
      >
        {children}
        <div
          ref={canvasRef}
          className="clip-panel-canvas clip-panel-canvas-fullvp"
          style={{
            height: '100vh',
            width: '100vw',
            background: 'transparent',
            overflow: 'visible',
            clipPath: 'none',
          }}
        >
          {viewportEl}
        </div>
      </div>
    )
  }

  return (
    <div
      ref={panelRef}
      className={`clip-panel ${className || ''}`}
      data-viewport-id={viewportId}
      data-wm-surface-id={wmSurface?.surfaceId}
      data-wm-layer-id={wmSurface?.layerId}
      style={{ width: panelWidth }}
      onPointerDown={stopEventPropagation}
    >
      {children}
      <div
        ref={canvasRef}
        className="clip-panel-canvas"
        style={{ height: canvasHeight, overflow: 'hidden', position: 'relative' }}
      >
        {viewportEl}
        {readOnly && bounds && interactionMode === 'preview' && (
          <div
            className="clip-panel-wheel-capture"
            aria-hidden="true"
            onWheel={handleReadOnlyWheelCapture}
            style={{
              position: 'absolute',
              inset: 0,
              zIndex: 10,
              pointerEvents: 'auto',
              background: 'transparent',
            }}
          />
        )}
      </div>
    </div>
  )
}
