/**
 * CanvasClipPanel — fork-viewport panel that shows a clipped region of the
 * main canvas. Used by ChangePreviewPanel, AnnotationViewer, ScreenshotCapture,
 * FleetHUD, FleetDocViewShape, and BuildErrorOverlay.
 *
 * Uses the tldraw fork's multi-viewport API:
 * - Registers a named viewport with the main editor
 * - Renders shapes visible to that viewport via getRenderingShapes({ viewportId })
 * - Independent camera without duplicating the store
 *
 * This replaces the old copy-store approach (separate editor + bidirectional sync).
 */
import { useEffect, useMemo, useRef } from 'react'
import { TldrawViewport, stopEventPropagation } from 'tldraw'
import type { Editor, TLAnyShapeUtilConstructor, TLStateNodeConstructor, TLShape, TLViewportId } from 'tldraw'
import { createCanvasClipPanelPlan } from './wm/canvas-clip-panel'
import { VisibilityViewportProvider } from './shapes/useIsInViewport'
import './CanvasClipPanel.css'

const DEFAULT_WIDTH = 600
const DEFAULT_MAX_HEIGHT_FRACTION = 0.4
const MIN_VISIBLE_LINES = 5
const LINE_HEIGHT_ESTIMATE = 14 // ~12pt in PDF coordinates

function getOptionalViewport(editor: Editor, viewportId: TLViewportId) {
  try {
    return editor.getViewport(viewportId)
  } catch (error) {
    if (error instanceof Error && error.message.includes('No viewport registered')) {
      return null
    }
    throw error
  }
}

export interface ClipBounds {
  x: number
  y: number
  w: number
  h: number
}

interface CanvasClipPanelProps {
  mainEditor: Editor
  bounds: ClipBounds | null
  // Legacy props (accepted but ignored — kept for consumer compatibility)
  shapeUtils?: TLAnyShapeUtilConstructor[]
  tools?: TLStateNodeConstructor[]
  licenseKey?: string
  panelWidth?: number
  maxHeightFraction?: number
  className?: string
  lockCamera?: boolean
  initialTool?: string
  onEditorMount?: (editor: Editor | null) => void
  emphasizeShapeIds?: string[]
  readOnly?: boolean
  liveEdit?: boolean
  cameraOverride?: { x: number; y: number; z: number }
  fullViewport?: boolean
  identityId?: string | null
  customGestureActiveRef?: { current: boolean }
  requestedShapeIds?: string[]
  requestedShapeTypes?: string[]
  /** External viewport ID (generated by parent). If not provided, generates one internally. */
  viewportId?: string
  children?: React.ReactNode
}

export function CanvasClipPanel({
  mainEditor,
  bounds,
  panelWidth = DEFAULT_WIDTH,
  maxHeightFraction = DEFAULT_MAX_HEIGHT_FRACTION,
  className,
  lockCamera = false,
  cameraOverride,
  fullViewport = false,
  readOnly = false,
  onEditorMount,
  viewportId: externalViewportId,
  children,
}: CanvasClipPanelProps) {
  const panelRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLDivElement>(null)
  const generatedViewportId = useMemo(() => `clip-panel-${Math.random().toString(36).slice(2, 9)}`, [])
  const viewportId = externalViewportId ?? generatedViewportId

  useEffect(() => {
    const shouldRouteWheel = (fullViewport && lockCamera) || readOnly
    if (!shouldRouteWheel) return
    const panel = panelRef.current
    if (!panel) return

    const onWheelCapture = (e: WheelEvent) => {
      const target = e.target instanceof Element ? e.target : null
      if (!target || e.ctrlKey || e.metaKey) return

      const chat = target.closest('.fleet-chat-shape') as HTMLElement | null
      if (chat) {
        const log = chat.querySelector('.fleet-chat-log') as HTMLElement | null
        if (!log || log.scrollHeight <= log.clientHeight) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        log.scrollTop += e.deltaY
        log.dispatchEvent(new CustomEvent('fleet-user-scroll'))
        return
      }

      const docview = target.closest('.fleet-docview') as HTMLElement | null
      if (docview) {
        const viewportHost = (target.closest('[data-viewport-id]') || docview.querySelector('[data-viewport-id]')) as HTMLElement | null
        const nestedViewportId = viewportHost?.dataset.viewportId as TLViewportId | undefined
        if (!nestedViewportId) return
        const registered = getOptionalViewport(mainEditor, nestedViewportId)
        if (!registered) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        const z = registered.camera.z || 1
        mainEditor.updateViewport(nestedViewportId, {
          camera: {
            ...registered.camera,
            x: registered.camera.x - e.deltaX / z,
            y: registered.camera.y - e.deltaY / z,
          },
        })
      }
    }

    panel.addEventListener('wheel', onWheelCapture, { capture: true, passive: false })
    return () => panel.removeEventListener('wheel', onWheelCapture, { capture: true })
  }, [fullViewport, lockCamera, mainEditor, readOnly])

  // Expose the main editor to consumers via onEditorMount.
  // With the fork viewport there is no separate overlay editor — consumers
  // use the main editor + viewportId for viewport-specific queries.
  useEffect(() => {
    onEditorMount?.(mainEditor ?? null)
    return () => { onEditorMount?.(null) }
  }, [mainEditor, onEditorMount])

  // Compute camera from bounds or use override
  const camera = useMemo(() => {
    if (cameraOverride) return cameraOverride
    if (!bounds) return { x: 0, y: 0, z: 1 }

    const plan = createCanvasClipPanelPlan({
      bounds,
      panelWidth,
      viewportHeight: window.innerHeight,
      maxHeightFraction,
      lockCamera,
      minVisibleLines: MIN_VISIBLE_LINES,
      lineHeightEstimate: LINE_HEIGHT_ESTIMATE,
    })

    return plan.camera
  }, [bounds, panelWidth, maxHeightFraction, lockCamera, cameraOverride])

  // Panel height: at least 5 lines, at most maxHeightFraction of viewport
  const canvasHeight = useMemo(() => {
    if (!bounds) return 100
    const zoom = panelWidth / bounds.w
    const contentH = bounds.h * zoom
    const minH = MIN_VISIBLE_LINES * LINE_HEIGHT_ESTIMATE * zoom
    return Math.max(minH, Math.min(contentH, window.innerHeight * maxHeightFraction))
  }, [bounds, panelWidth, maxHeightFraction])

  if (!bounds && !cameraOverride) return null

  // Shape predicate: filter shapes based on mode
  const shapePredicate = useMemo(() => {
    if (!lockCamera && !readOnly) return undefined

    return (shape: TLShape) => {
      // In lockCamera (HUD) mode, only render fleet shapes
      if (lockCamera) {
        const type = (shape as any).type
        if (!type) return false
        // Fleet shape types: fleet-chat, fleet-agents, etc.
        if (!type.startsWith('fleet-')) return false
        const props = (shape as any).props
        if (!props) return false
        const uid = props.userId
        const dev = props.deviceId
        return !!uid && !!dev
      }

      // In readOnly mode, render all shapes
      return true
    }
  }, [lockCamera, readOnly])

  const viewportEl = (
    <VisibilityViewportProvider viewportId={viewportId}>
      <TldrawViewport
        id={viewportId}
        camera={camera}
        className={className}
        shapePredicate={shapePredicate}
        onCameraChange={lockCamera ? undefined : (newCam) => {
          // For non-locked panels, allow user to pan/zoom
          console.log('[CanvasClipPanel] camera change:', newCam)
        }}
      />
    </VisibilityViewportProvider>
  )

  if (fullViewport) {
    return (
      <div
        ref={panelRef}
        className={`clip-panel clip-panel-fullvp ${className || ''}`}
        data-viewport-id={viewportId}
        style={{
          position: 'fixed',
          inset: 0,
          width: '100vw',
          height: '100vh',
          pointerEvents: 'none',
          background: 'transparent',
          boxShadow: 'none',
          borderRadius: 0,
          overflow: 'visible',
        }}
      >
        {children}
        <div
          ref={canvasRef}
          className="clip-panel-canvas clip-panel-canvas-fullvp"
          style={{
            height: '100vh',
            width: '100vw',
            background: 'transparent',
            overflow: 'visible',
            clipPath: 'none',
          }}
        >
          {viewportEl}
        </div>
      </div>
    )
  }

  return (
    <div
      ref={panelRef}
      className={`clip-panel ${className || ''}`}
      data-viewport-id={viewportId}
      style={{ width: panelWidth }}
      onPointerDown={stopEventPropagation}
    >
      {children}
      <div
        ref={canvasRef}
        className="clip-panel-canvas"
        style={{ height: canvasHeight, overflow: 'hidden' }}
      >
        {viewportEl}
      </div>
    </div>
  )
}
