/**
 * CanvasClipPanel — fork-viewport panel that shows a clipped region of the
 * main canvas. Used by ChangePreviewPanel, AnnotationViewer, ScreenshotCapture,
 * FleetHUD, FleetDocViewShape, and BuildErrorOverlay.
 *
 * Uses the tldraw fork's multi-viewport API:
 * - Registers a named viewport with the main editor
 * - Renders shapes visible to that viewport via getRenderingShapes({ viewportId })
 * - Independent camera without duplicating the store
 *
 * This replaces the old copy-store approach (separate editor + bidirectional sync).
 */
import { useEffect, useMemo, useRef, useState } from 'react'
import { TldrawViewport, Vec, stopEventPropagation } from 'tldraw'
import type { Editor, TLAnyShapeUtilConstructor, TLStateNodeConstructor, TLShape, TLViewportId } from 'tldraw'
import { createCanvasClipPanelPlan, shouldRenderLockedFleetViewportShape } from './wm/canvas-clip-panel'
import type { WMCore } from './wm/wm-core'
import {
  cameraToCoordinateTransform,
  ensureLayer,
  registerViewportLayer,
  removeLayers,
  unregisterViewportLayer,
  viewportCoordinateLayerId,
  viewportFrameLayerId,
} from './wm/editor-wm'
import { VisibilityViewportProvider } from './shapes/useIsInViewport'
import { getDeviceId, isDeviceReady } from './fleet/fleet-data.mjs'
import './CanvasClipPanel.css'

const DEFAULT_WIDTH = 600
const DEFAULT_MAX_HEIGHT_FRACTION = 0.4
const MIN_VISIBLE_LINES = 5
const LINE_HEIGHT_ESTIMATE = 14 // ~12pt in PDF coordinates

function getOptionalViewport(editor: Editor, viewportId: TLViewportId) {
  try {
    return editor.getViewport(viewportId)
  } catch (error) {
    if (error instanceof Error && error.message.includes('No viewport registered')) {
      return null
    }
    throw error
  }
}

interface CanvasClipWMSurface {
  wm: WMCore
  layerId: string
  surfaceId?: string
}

const wmSurfaceRegistry = new Map<string, {
  surface: CanvasClipWMSurface
  setCamera: (camera: { x: number; y: number; z: number }) => void
  syncViewportCamera: (camera: { x: number; y: number; z: number }) => void
}>()

function sameCamera(a: { x: number; y: number; z: number } | null, b: { x: number; y: number; z: number }) {
  return !!a && a.x === b.x && a.y === b.y && a.z === b.z
}

function wmSurfaceCamera(surface: CanvasClipWMSurface, fullViewport: boolean) {
  const transform = fullViewport
    ? surface.wm.transform(surface.layerId)
    : surface.wm.transformInfo(surface.layerId).local
  return { x: transform.x, y: transform.y, z: transform.scale }
}

function applyViewportCameraToDom(canvas: HTMLDivElement | null, camera: { x: number; y: number; z: number }) {
  const htmlLayer = canvas?.querySelector<HTMLElement>('.tl-html-layer.tl-shapes')
  if (!htmlLayer) return
  htmlLayer.style.transform = `scale(${camera.z}) translate(${camera.x}px,${camera.y}px)`
}

function setSurfaceCamera(surface: CanvasClipWMSurface, camera: { x: number; y: number; z: number }) {
  const layer = surface.wm.getLayer(surface.layerId)
  if (layer.policy.x === 'pin' && layer.policy.y === 'pin' && layer.policy.zoom === 'lock') {
    surface.wm.setTransform(surface.layerId, { x: camera.x, y: camera.y, scale: camera.z })
    surface.wm.setCamera(surface.layerId, { x: 0, y: 0, z: 1 })
    return
  }
  surface.wm.setCamera(surface.layerId, camera)
}

function isEditableWheelTarget(target: Element) {
  return !!target.closest('input, textarea, select, button, a, [contenteditable="true"], [role="button"]')
}

function dispatchMainCanvasWheel(mainEditor: Editor, e: WheelEvent) {
  mainEditor.focus({ focusContainer: false })
  mainEditor.dispatch({
    type: 'wheel',
    name: 'wheel',
    delta: new Vec(-e.deltaX, -e.deltaY, 0),
    point: new Vec(e.clientX, e.clientY),
    shiftKey: e.shiftKey,
    altKey: e.altKey,
    ctrlKey: e.metaKey || e.ctrlKey,
    metaKey: e.metaKey,
    accelKey: e.metaKey || e.ctrlKey,
  })
}

export function syncCanvasClipPanelViewportCamera(
  viewportId: string,
  camera: { x: number; y: number; z: number },
): boolean {
  const registered = wmSurfaceRegistry.get(viewportId)
  if (!registered) return false
  registered.syncViewportCamera(camera)
  return true
}

export interface ClipBounds {
  x: number
  y: number
  w: number
  h: number
}

interface CanvasClipPanelProps {
  mainEditor: Editor
  bounds: ClipBounds | null
  // Legacy props (accepted but ignored — kept for consumer compatibility)
  shapeUtils?: TLAnyShapeUtilConstructor[]
  tools?: TLStateNodeConstructor[]
  licenseKey?: string
  panelWidth?: number
  maxHeightFraction?: number
  className?: string
  lockCamera?: boolean
  initialTool?: string
  onEditorMount?: (editor: Editor | null) => void
  emphasizeShapeIds?: string[]
  readOnly?: boolean
  liveEdit?: boolean
  wmSurface?: CanvasClipWMSurface
  fullViewport?: boolean
  identityId?: string | null
  customGestureActiveRef?: { current: boolean }
  requestedShapeIds?: string[]
  requestedShapeTypes?: string[]
  /** External viewport ID (generated by parent). If not provided, generates one internally. */
  viewportId?: string
  children?: React.ReactNode
}

export function CanvasClipPanel({
  mainEditor,
  bounds,
  panelWidth = DEFAULT_WIDTH,
  maxHeightFraction = DEFAULT_MAX_HEIGHT_FRACTION,
  className,
  lockCamera = false,
  wmSurface,
  fullViewport = false,
  readOnly = false,
  onEditorMount,
  identityId,
  viewportId: externalViewportId,
  children,
  requestedShapeIds,
  requestedShapeTypes,
}: CanvasClipPanelProps) {
  const panelRef = useRef<HTMLDivElement>(null)
  const canvasRef = useRef<HTMLDivElement>(null)
  const generatedViewportId = useMemo(() => `clip-panel-${Math.random().toString(36).slice(2, 9)}`, [])
  const viewportId = externalViewportId ?? generatedViewportId

  useEffect(() => {
    const shouldRouteWheel = (fullViewport && lockCamera) || readOnly
    if (!shouldRouteWheel) return
    const panel = panelRef.current
    if (!panel) return

    const onWheelCapture = (e: WheelEvent) => {
      const target = e.target instanceof Element ? e.target : null
      if (!target || e.ctrlKey || e.metaKey) return

      const chat = target.closest('.fleet-chat-shape') as HTMLElement | null
      if (chat) {
        const log = target.closest('.fleet-chat-log') as HTMLElement | null
        if (!log) {
          if (Math.abs(e.deltaX) > Math.abs(e.deltaY) && !isEditableWheelTarget(target)) {
            e.preventDefault()
            e.stopPropagation()
            e.stopImmediatePropagation()
            dispatchMainCanvasWheel(mainEditor, e)
          }
          return
        }
        if (log.scrollHeight <= log.clientHeight) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        log.scrollTop += e.deltaY
        log.dispatchEvent(new CustomEvent('fleet-user-scroll'))
        return
      }

      const docview = target.closest('.fleet-docview') as HTMLElement | null
      if (docview) {
        const viewportHost = (target.closest('[data-viewport-id]') || docview.querySelector('[data-viewport-id]')) as HTMLElement | null
        const nestedViewportId = viewportHost?.dataset.viewportId as TLViewportId | undefined
        if (!nestedViewportId) return
        const registered = getOptionalViewport(mainEditor, nestedViewportId)
        if (!registered) return
        e.preventDefault()
        e.stopPropagation()
        e.stopImmediatePropagation()
        const z = registered.camera.z || 1
        const nextCamera = {
          ...registered.camera,
          x: registered.camera.x - e.deltaX / z,
          y: registered.camera.y - e.deltaY / z,
        }
        const nestedSurface = wmSurfaceRegistry.get(nestedViewportId)
        if (nestedSurface) nestedSurface.setCamera(nextCamera)
      }
    }

    panel.addEventListener('wheel', onWheelCapture, { capture: true, passive: false })
    return () => panel.removeEventListener('wheel', onWheelCapture, { capture: true })
  }, [fullViewport, lockCamera, mainEditor, readOnly])

  useEffect(() => {
    if (!wmSurface) return
    const syncViewportCamera = (camera: { x: number; y: number; z: number }) => {
      const viewport = getOptionalViewport(mainEditor, viewportId as TLViewportId)
      if (viewport?.screenBounds) {
        mainEditor.updateViewport(viewportId as TLViewportId, { camera })
      }
      applyViewportCameraToDom(canvasRef.current, camera)
    }
    const setCamera = (camera: { x: number; y: number; z: number }) => {
      setSurfaceCamera(wmSurface, camera)
      syncViewportCamera(wmSurfaceCamera(wmSurface, fullViewport))
    }
    wmSurfaceRegistry.set(viewportId, { surface: wmSurface, setCamera, syncViewportCamera })
    return () => {
      const registered = wmSurfaceRegistry.get(viewportId)
      if (registered?.surface === wmSurface) wmSurfaceRegistry.delete(viewportId)
    }
  }, [mainEditor, viewportId, wmSurface, fullViewport])

  // Expose the main editor to consumers via onEditorMount.
  // With the fork viewport there is no separate overlay editor — consumers
  // use the main editor + viewportId for viewport-specific queries.
  useEffect(() => {
    onEditorMount?.(mainEditor ?? null)
    return () => { onEditorMount?.(null) }
  }, [mainEditor, onEditorMount])

  // Compute camera from bounds or use WM surface. Deduplicate by value: when
  // FleetHUD re-renders (e.g. on fleetBounds recalc) the source produces a new
  // camera object with the same x/y/z. Without dedup, TldrawViewport receives a
  // new camera prop reference, re-registers the viewport, and useIsInViewport's
  // useValue recomputes — which can briefly flip isInViewport false, unmounting
  // FleetChatInner/FleetAgentsInner (the remount bug, 2026-06-22, commit 1517e737).
  const stableCameraRef = useRef<{ x: number; y: number; z: number } | null>(null)
  const [interactiveCamera, setInteractiveCamera] = useState<{ x: number; y: number; z: number } | null>(null)
  const plannedCamera = (() => {
    const next = (() => {
      if (wmSurface) return wmSurfaceCamera(wmSurface, fullViewport)
      if (!bounds) return { x: 0, y: 0, z: 1 }
      return createCanvasClipPanelPlan({
        bounds, panelWidth, viewportHeight: window.innerHeight,
        maxHeightFraction, lockCamera,
        minVisibleLines: MIN_VISIBLE_LINES, lineHeightEstimate: LINE_HEIGHT_ESTIMATE,
      }).camera
    })()
    const prev = stableCameraRef.current
    if (prev && prev.x === next.x && prev.y === next.y && prev.z === next.z) return prev
    stableCameraRef.current = next
    return next
  })()
  const camera = interactiveCamera ?? plannedCamera

  useEffect(() => {
    setInteractiveCamera(null)
  }, [plannedCamera])

  useEffect(() => {
    if (!wmSurface) return
    const frameLayerId = viewportFrameLayerId(viewportId as TLViewportId)
    const coordinateLayerId = viewportCoordinateLayerId(viewportId as TLViewportId)
    const readFrame = () => {
      const currentRect = panelRef.current?.getBoundingClientRect()
      return {
        x: fullViewport ? 0 : currentRect?.left ?? 0,
        y: fullViewport ? 0 : currentRect?.top ?? 0,
        scale: 1,
      }
    }
    ensureLayer(wmSurface.wm, frameLayerId, {
      parent: wmSurface.wm.rootLayerId,
      policy: { x: 'pin', y: 'pin', zoom: 'lock' },
      transform: readFrame(),
    })
    ensureLayer(wmSurface.wm, coordinateLayerId, {
      parent: frameLayerId,
      policy: { x: 'pin', y: 'pin', zoom: 'lock' },
      transform: cameraToCoordinateTransform(camera),
      camera: { x: 0, y: 0, z: 1 },
    })
    const registration = {
      viewportId: viewportId as TLViewportId,
      wm: wmSurface.wm,
      frameLayerId,
      coordinateLayerId,
      surfaceLayerId: wmSurface.layerId,
      readFrame,
    }
    registerViewportLayer(mainEditor, registration)
    return () => {
      unregisterViewportLayer(mainEditor, viewportId as TLViewportId, registration)
      removeLayers(wmSurface.wm, [coordinateLayerId, frameLayerId])
    }
  }, [mainEditor, wmSurface, viewportId, fullViewport, camera.x, camera.y, camera.z])

  // Panel height: at least 5 lines, at most maxHeightFraction of viewport
  const canvasHeight = useMemo(() => {
    if (!bounds) return 100
    const zoom = panelWidth / bounds.w
    const contentH = bounds.h * zoom
    const minH = MIN_VISIBLE_LINES * LINE_HEIGHT_ESTIMATE * zoom
    return Math.max(minH, Math.min(contentH, window.innerHeight * maxHeightFraction))
  }, [bounds, panelWidth, maxHeightFraction])

  if (!bounds && !wmSurface) return null

  // Shape predicate: filter shapes based on mode
  const requestedIdSet = useMemo(() => {
    return requestedShapeIds?.length ? new Set(requestedShapeIds) : null
  }, [requestedShapeIds])
  const requestedTypeSet = useMemo(() => {
    return requestedShapeTypes?.length ? new Set(requestedShapeTypes) : null
  }, [requestedShapeTypes])
  const shapePredicate = useMemo(() => {
    if (requestedIdSet || requestedTypeSet) {
      return (shape: TLShape) => {
        if (requestedIdSet && !requestedIdSet.has(shape.id)) return false
        if (requestedTypeSet && !requestedTypeSet.has(shape.type)) return false
        return true
      }
    }

    if (!lockCamera && !readOnly) return undefined

    return (shape: TLShape) => {
      // In lockCamera (HUD) mode, only render fleet shapes
      if (lockCamera) {
        return shouldRenderLockedFleetViewportShape(shape, {
          userId: identityId,
          deviceId: isDeviceReady() ? getDeviceId() : '',
        })
      }

      // In readOnly mode, render all shapes
      return true
    }
  }, [identityId, lockCamera, readOnly, requestedIdSet, requestedTypeSet])

  const viewportEl = (
    <VisibilityViewportProvider viewportId={viewportId}>
      <TldrawViewport
        id={viewportId}
        camera={camera}
        className={className}
        shapePredicate={shapePredicate}
        onCameraChange={lockCamera ? undefined : (newCam) => {
          setInteractiveCamera(prev => sameCamera(prev, newCam) ? prev : newCam)
        }}
      />
    </VisibilityViewportProvider>
  )

  if (fullViewport) {
    return (
      <div
        ref={panelRef}
        className={`clip-panel clip-panel-fullvp ${className || ''}`}
        data-viewport-id={viewportId}
        data-wm-surface-id={wmSurface?.surfaceId}
        data-wm-layer-id={wmSurface?.layerId}
        style={{
          position: 'fixed',
          inset: 0,
          width: '100vw',
          height: '100vh',
          pointerEvents: 'none',
          background: 'transparent',
          boxShadow: 'none',
          borderRadius: 0,
          overflow: 'visible',
        }}
      >
        {children}
        <div
          ref={canvasRef}
          className="clip-panel-canvas clip-panel-canvas-fullvp"
          style={{
            height: '100vh',
            width: '100vw',
            background: 'transparent',
            overflow: 'visible',
            clipPath: 'none',
          }}
        >
          {viewportEl}
        </div>
      </div>
    )
  }

  return (
    <div
      ref={panelRef}
      className={`clip-panel ${className || ''}`}
      data-viewport-id={viewportId}
      data-wm-surface-id={wmSurface?.surfaceId}
      data-wm-layer-id={wmSurface?.layerId}
      style={{ width: panelWidth }}
      onPointerDown={stopEventPropagation}
    >
      {children}
      <div
        ref={canvasRef}
        className="clip-panel-canvas"
        style={{ height: canvasHeight, overflow: 'hidden' }}
      >
        {viewportEl}
      </div>
    </div>
  )
}
